### ISSUE TITLE
Store SNP step returns an Error

### ISSUE THREAD

**Issue by maxpletner** [opentap/Network-Analyzer#47]
One of the students at S1000 has discovered such a bug during the lab with the VNA Simulator.

_2023-06-26 17:05:16.732432 ; TestPlan       ; Error       ; Error running "Store SNP": Object reference not set to an instance of an object..
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ; NullReferenceException: Object reference not set to an instance of an object.
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at OpenTap.Plugins.PNAX.LMS.StoreSnpAdvanced.Run()
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at OpenTap.TestStepExtensions.DoRun(ITestStep Step, TestPlanRun planRun, TestRun parentRun, IEnumerable`1 attachedParameters)
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ; Exception caught at:
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at failState execTestPlan(OpenTap.TestPlanRun, System.Collections.Generic.IList`1[OpenTap.ITestStep])
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at OpenTap.TestPlanRun DoExecute(System.Collections.Generic.IEnumerable`1[OpenTap.IResultListener], System.Collections.Generic.IEnumerable`1[OpenTap.ResultParameter], System.Collections.Generic.HashSet`1[OpenTap.ITestStep])
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at OpenTap.TestPlanRun executeInContext(System.Collections.Generic.IEnumerable`1[OpenTap.IResultListener], System.Collections.Generic.IEnumerable`1[OpenTap.ResultParameter], System.Collections.Generic.HashSet`1[OpenTap.ITestStep])
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     at Void g()
2023-06-26 17:05:16.732432 ; TestPlan       ; Debug       ;     ...
2023-06-26 17:05:16.732432 ; TestPlan       ; Information ; "Store SNP" completed with verdict 'Error'. [2.47 ms]_

All licenses are fine, the log file is attached.
It's the only time we've found such an issue - still requires some attention.
The VNA Offline Simulator has a previous FW version.
Old: A.17.05.08
New:  A.17.19.16 - it solved the issue
[SessionLog 2023-06-26 16-59-31.txt](https://github.com/opentap/Network-Analyzer/files/11908203/SessionLog.2023-06-26.16-59-31.txt)

**Comment by AsgerIversen** [comment]
I think I ran into this yesterday during a demo.

[SessionLogs-2026-04-08-13_23_03.log](https://github.com/user-attachments/files/26566819/SessionLogs-2026-04-08-13_23_03.log)

The AI really likes to put that "Store SNP" step into test plans, and then it gets all confused about this error.

**Comment by noxdk** [comment]
These are two different scenarios of a `NullReferenceException`. I have created a PR that fixes the one @maxpletner experienced. The one you experienced @AsgerIversen was not really a bug in this plugin itself, but it could be hard for the end user to find out what is wrong. I have added a possible explanation of what to do in this case.

The PR also enables querying for errors if an exception is thrown when doing a SCPI query.
